### ISSUE TITLE
HW2 feedback

### ISSUE THREAD

**Issue by ntjames** [ok-tsar/homework#2]
@rstojsin, your .md file doesn't match your .Rmd file. I didn't see any major issues scanning the .Rmd, but can you push the updated .md?

**Comment by ok-tsar** [comment]
I have no idea what the md file is/what it does? i have updated it but I dont know if thats what you want in it. let me know if its not.

pushing now!
________________________________

**Comment by ntjames** [comment]
Hi @rstojsin, 

The .Rmd file contains the raw code which is not rendered on GitHub, it just shows up as plaintext code. If you knit the .Rmd file in Rstudio it will automatically produce a .md file and a figure directory and plots. Viewing the .md on GitHub will show the code, the output and the plots.

You should be able to get the correct output by opening the .Rmd, knitting the document, and then pushing the updated .md, figure directory and plots to the repo. Let me know if you have any questions

**Comment by ntjames** [comment]
Hi @rstojsin,

Your updated code looks good and I've marked this assignment down as a pass. My only comment is that tuning lambda typically involves selecting a specific value. E.g., state what value of lambda you would use and why
